# Generated by Django 2.2.3 on 2019-08-06 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time_tracker.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('avatar', models.FileField(blank=True, upload_to=time_tracker.models.get_image_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', tinymce.models.HTMLField()),
                ('slug', models.SlugField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('kind', models.CharField(choices=[('F', 'Feature'), ('B', 'Bug')], default='F', max_length=1)),
                ('priority', models.CharField(choices=[('N', 'Normal'), ('H', 'High'), ('U', 'Urgent')], default='N', max_length=1)),
                ('hours', models.FloatField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('implementer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_implementer', to='time_tracker.Developer')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tracker.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('comment', models.TextField()),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tracker.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tracker.Developer')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tracker.Task')),
            ],
        ),
    ]
